// @ts-nocheck
// Generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Quit the entire application. The floating pill has no native window chrome,
 * so the frontend needs an explicit way to exit (exposed from Settings, and
 * from the tray menu — see [`crate::tray`]).
 */
async quit() : Promise<void> {
    await TAURI_INVOKE("quit");
},
/**
 * Whether Echo is registered to start when the user logs in.
 * 
 * Read from the OS every time rather than cached in `echo.db`. The
 * registration lives outside Echo — a registry Run key, a LaunchAgent plist,
 * an XDG autostart entry — and a user who removes it with the OS's own tools
 * would otherwise see a settings toggle that lies about the state of their
 * machine.
 * 
 * A platform that cannot answer reports `false` rather than failing, so
 * Settings renders an honest "off" instead of an error where the feature
 * simply does not apply.
 */
async getAutostart() : Promise<boolean> {
    return await TAURI_INVOKE("get_autostart");
},
/**
 * Register or unregister Echo as a login item.
 */
async setAutostart(enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The logged-in account's given name, for the greeting on the Dictation page.
 * 
 * Echo has no account of its own and asks for nothing, so this is the only
 * name available without inventing a settings field nobody wants to fill in.
 * The OS is the source: `USERNAME` on Windows, `USER` elsewhere.
 * 
 * `None` rather than a guess when the variable is missing, or holds something
 * that is plainly a machine account rather than a person — a greeting that
 * says "Hey root" or "Hey Administrator" is worse than one with no name in it.
 * The frontend drops the name and greets anyway.
 */
async accountName() : Promise<string | null> {
    return await TAURI_INVOKE("account_name");
},
async getAudioDevices() : Promise<Result<AudioDevice[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Listen for a few seconds and report how loud the input actually is.
 * 
 * Refuses while a dictation is running rather than stealing the stream from
 * it: the device is shared, and the words being spoken belong to the
 * recording, not to a test.
 */
async testInputLevel(device: string | null) : Promise<Result<InputTest, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_input_level", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the Whisper model catalog with local download status.
 */
async listModels() : Promise<ModelInfo[]> {
    return await TAURI_INVOKE("list_models");
},
/**
 * Download the NeMo-Speech binaries for this machine.
 */
async downloadNemoEngine() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_nemo_engine") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async nemoStatus() : Promise<NemoStatus> {
    return await TAURI_INVOKE("nemo_status");
},
/**
 * Download a model, emitting `echo://model-download-progress` updates and a
 * final `echo://model-download-complete` event.
 */
async downloadModel(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch the active ASR provider, persisting the choice. Selecting `"local"`
 * (re)builds the Whisper provider from the bundled binary + selected model.
 */
async setAsrProvider(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_asr_provider", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the selected local model and reload whichever engine owns it.
 * 
 * One command for both engines because the picker is one list: the catalog
 * says which engine a model belongs to, so choosing a NeMo model switches the
 * engine rather than asking the user to do it in two places.
 */
async setWhisperModel(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_whisper_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a downloaded model's weights, freeing the disk they occupy.
 * 
 * Refuses to remove the model the local engine is set to use: that would leave
 * transcription silently broken with nothing on screen explaining why.
 */
async deleteModel(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the local engine is ready to transcribe (binary + selected model
 * both present). Used by onboarding and settings to gate the local option.
 */
async whisperReady() : Promise<boolean> {
    return await TAURI_INVOKE("whisper_ready");
},
/**
 * Download the whisper-cli binary for this platform, emitting
 * `echo://whisper-binary-progress` (bare f32, 0..1). On platforms without a
 * prebuilt release this errors with guidance to install one on PATH.
 */
async downloadWhisperBinary() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_whisper_binary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gpuStatus() : Promise<GpuStatus> {
    return await TAURI_INVOKE("gpu_status");
},
/**
 * Download the accelerated whisper.cpp build this machine can run, emitting
 * `echo://whisper-binary-progress` (bare f32, 0..1).
 */
async downloadGpuPack() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_gpu_pack") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turn GPU decoding on or off. Also clears a latched failure, so this doubles
 * as the "try the GPU again" control after fixing a driver.
 */
async setGpuEnabled(enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_gpu_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pin the decode thread count, or pass "auto" to let Echo choose.
 */
async setWhisperThreads(threads: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_whisper_threads", { threads }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ids of every binary pack currently installed on disk. Lets the settings UI
 * offer to reclaim the disk a superseded pack is using.
 */
async installedPacks() : Promise<string[]> {
    return await TAURI_INVOKE("installed_packs");
},
/**
 * Transcribe an audio file with the local Whisper engine, or — with
 * `speakers` — with the active cloud engine, labelled by speaker.
 * 
 * The dictionary is applied to the result exactly as it is for dictation, so
 * an imported transcript spells names the same way a dictated one does.
 */
async transcribeFile(path: string, language: string | null, speakers: boolean | null) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_file", { path, language, speakers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The formats this can accept, for a file-picker filter.
 */
async supportedImportFormats() : Promise<string[]> {
    return await TAURI_INVOKE("supported_import_formats");
},
async startRecording(deviceName: string | null, language: string | null) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { deviceName, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
/**
 * Open the microphone before it is needed, so the recording that follows
 * starts instantly and keeps the half-second before the key press.
 * 
 * Called on the interactions that reliably precede a dictation — pressing the
 * pill, arming the hotkey. Best-effort by design: it returns nothing and fails
 * silently, because a failed warm-up must never stop a recording from starting
 * the ordinary way.
 */
async warmMicrophone() : Promise<void> {
    await TAURI_INVOKE("warm_microphone");
},
async listDictionary() : Promise<Result<DictionaryEntry[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addDictionaryEntry(phrase: string, replacement: string) : Promise<Result<number, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictionary_entry", { phrase, replacement }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDictionaryEntry(id: number) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictionary_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleDictionaryEntry(id: number, enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_dictionary_entry", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Serialize all entries and snippets to a JSON file at the user-chosen path.
 */
async exportDictionary(path: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_dictionary", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a JSON file and insert entries whose phrase isn't already present
 * (case-insensitive), and snippets whose trigger isn't. Returns the number of
 * entries and snippets added.
 */
async importDictionary(path: string) : Promise<Result<number, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_dictionary", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Learn dictionary entries from a transcript the user corrected by hand.
 * 
 * Returns the corrections that were actually stored, so the UI can show what
 * it learned. Learning nothing is a normal outcome — most edits are rewording,
 * not corrections — and is reported as an empty list rather than an error.
 * 
 * Entries land in the ordinary dictionary, visible and deletable like any
 * other. That is the safety net for the heuristic in
 * [`crate::core::dictionary::learn`]: anything it gets wrong is one click away
 * from being removed, rather than an invisible rule the user cannot find.
 */
async learnFromCorrection(original: string, edited: string) : Promise<Result<DictionaryExportEntry[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("learn_from_correction", { original, edited }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync now, from the button. The window also calls this after the folder or
 * the switch changes, so the result shows at once rather than on the next poll.
 */
async syncDictionaryNow() : Promise<Result<DictionarySyncStatus, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_dictionary_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDictionarySyncStatus() : Promise<DictionarySyncStatus> {
    return await TAURI_INVOKE("get_dictionary_sync_status");
},
async listSnippets() : Promise<Result<Snippet[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a snippet (`id: None`) or update one. Returns its id.
 */
async saveSnippet(snippet: Snippet) : Promise<Result<number, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snippet", { snippet }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnippet(id: number) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory(limit: number | null) : Promise<Result<TranscriptionRecord[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What dictation has added up to, for the stats card.
 * 
 * Derived from History, so it is empty when History is off — which is the
 * honest outcome: there is nothing to count, rather than a number invented
 * from somewhere else.
 */
async getDictationStats() : Promise<Result<DictationStats, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dictation_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Insights page, in one call.
 * 
 * Same source and the same caveat as [`get_dictation_stats`]: it is History,
 * so it is empty when History is off.
 */
async getInsights() : Promise<Result<Insights, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_insights") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the OS grants this app permission to synthesize keystrokes.
 * 
 * On macOS this reflects the Accessibility permission; other platforms don't
 * gate keyboard injection, so they always return `true`.
 */
async checkAccessibilityPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_accessibility_permission");
},
/**
 * Type `text` into the focused application. Used by the History panel to
 * re-insert a past transcript and by onboarding to test text output.
 */
async injectText(text: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inject_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether this machine can tell a password field from an ordinary one, and
 * for which apps.
 * 
 * Surfaced next to the guard's toggle: on Linux the answer depends on the
 * session, and a user who believes they are protected when they are not is
 * worse off than one who knows. Asking costs a D-Bus round trip there, so it
 * runs off the async runtime.
 */
async secureFieldDetection() : Promise<Detection> {
    return await TAURI_INVOKE("secure_field_detection");
},
/**
 * The currently configured global hotkey (or the default).
 */
async getHotkey() : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace the registered global hotkey and persist it.
 * 
 * Bound before it is saved, so a shortcut the system refuses leaves the
 * working one in place instead of persisting something that does nothing.
 * Whatever is already stored is honoured as-is — the picker is where new
 * bindings are vetted, and rejecting an old one here would only strand the
 * user with a hotkey they cannot change.
 */
async registerHotkey(shortcut: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_hotkey", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether global hotkeys can work in this desktop session, and what to do if
 * they cannot.
 * 
 * Surfaced in Settings beside the hotkey picker, because the failure this
 * describes is silent: on Wayland the shortcut registers without complaint and
 * then never fires.
 */
async hotkeySupport() : Promise<HotkeySupport> {
    return await TAURI_INVOKE("hotkey_support");
},
/**
 * Persist the recording mode and rebind the hotkey to match.
 * 
 * Hold-to-talk needs the key's release as well as its press, and for a bare
 * modifier it also needs a different rule for telling a hold from a chord — so
 * the binding is not independent of the mode.
 */
async setRecordingMode(mode: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_recording_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change one of the fix-up shortcuts (undo or retry) and persist it.
 * 
 * Unlike the dictation hotkey this saves first and then rebinds everything:
 * there is no "replace one shortcut" call in the plugin, so unbinding only
 * happens by way of the `unregister_all` inside [`bind`]. A shortcut the
 * system refuses is reported by [`bind_fixups`] and leaves the rest working.
 * Pass [`UNBOUND`] to turn one off.
 */
async setFixupHotkey(which: string, shortcut: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_fixup_hotkey", { which, shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The fix-up shortcuts as currently configured.
 */
async getFixupHotkeys() : Promise<[string, string]> {
    return await TAURI_INVOKE("get_fixup_hotkeys");
},
/**
 * Take back the last thing Echo typed into another application.
 * 
 * Returns whether there was anything to undo, so the caller can stay quiet
 * rather than reporting a failure when the answer is simply "nothing yet".
 */
async undoLastInsert() : Promise<Result<boolean, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_last_insert") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-decode the last utterance and replace what was typed with the result.
 * 
 * The audio is the one already in memory, so nothing has to be said again.
 * What changes is the decoder: [`retry_target`] picks a stronger local model
 * by default, and a cloud provider only if the user chose one.
 */
async retryLast() : Promise<Result<string | null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_last") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the retry can be pointed at: every registered provider, plus every
 * local model that is actually downloaded.
 */
async retryTargets() : Promise<Result<string[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_targets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a provider's API key in the OS keychain and register it for immediate
 * use (no restart needed).
 */
async setApiKey(provider: string, key: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report whether a provider has an API key stored. Never returns the key
 * itself (architectural rule 5).
 */
async getApiKeySet(provider: string) : Promise<Result<boolean, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_api_key_set", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a provider's stored API key from the keychain.
 */
async removeApiKey(provider: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The provider list the settings UI renders — replacing the arrays that used
 * to be duplicated in `CloudProviders.tsx` and `SettingsPanel.tsx`.
 */
async listCloudProviders() : Promise<Result<ProviderInfo[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_cloud_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save one of a provider's non-secret settings (model, endpoint, region) and
 * rebuild it so the change takes effect without a restart.
 */
async setProviderSetting(provider: string, field: string, value: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_setting", { provider, field, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transcribe a short silent buffer to prove the key, endpoint and model all
 * work together.
 * 
 * Worth a round trip: without it the first sign of a typo'd key is a sentence
 * that goes nowhere, mid-thought, with the error buried in a log. A provider
 * that returns empty text for silence has still answered the only question
 * being asked, so empty is a pass.
 */
async testApiKey(provider: string) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Counts of locally stored telemetry events, grouped by type.
 */
async getTelemetrySummary() : Promise<Result<TelemetrySummaryItem[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_telemetry_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete all locally stored telemetry events.
 */
async clearTelemetry() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_telemetry") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable or disable telemetry collection (persists the choice).
 */
async setTelemetryEnabled(enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_telemetry_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a usage event from the frontend (e.g. transcription_complete). Only
 * non-sensitive metadata should be passed — never transcript text or audio.
 */
async recordTelemetryEvent(eventType: string, payload: JsonValue | null) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_telemetry_event", { eventType, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlugins() : Promise<Result<PluginInfo[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the manifest next to a candidate library **without installing it**, so
 * the UI can show what the plugin claims it needs before anything is loaded.
 */
async inspectPlugin(path: string) : Promise<Result<PluginManifest, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_plugin", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install a plugin from a shared library path. Expects a `plugin.json` manifest
 * in the same directory. Copies both into the plugins directory, registers it,
 * and loads it.
 * 
 * `acknowledged` must be true: the caller has to have shown the user the
 * declared permissions *and* the fact that a plugin runs in-process with full
 * host privileges. This is a consent gate, not a sandbox — it cannot stop a
 * malicious plugin, it only stops one being loaded without the user being told.
 */
async installPlugin(path: string, acknowledged: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_plugin", { path, acknowledged }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enablePlugin(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_plugin", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disablePlugin(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_plugin", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uninstallPlugin(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_plugin", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a starter plugin project into `parent_dir/<name>/` and return the
 * directory it created.
 * 
 * `parent_dir` comes from the native folder picker, so the user has already
 * chosen where this lands. `name` is typed, which is why it is validated
 * rather than trusted: it becomes a path segment underneath that folder.
 */
async scaffoldPlugin(parentDir: string, name: string) : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scaffold_plugin", { parentDir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turn wake-word listening on or off, persisting the choice.
 */
async setWakeWordEnabled(enabled: boolean) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Select the wake phrase, restarting the listener so the change takes effect
 * without a relaunch.
 */
async setWakeWordModel(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the detection threshold (0.05..0.99 — lower catches more and misfires
 * more) and restart the listener with it.
 */
async setWakeWordSensitivity(threshold: number) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_wake_word_sensitivity", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The wake phrase catalog with local download status.
 */
async listWakeWords() : Promise<WakePhraseInfo[]> {
    return await TAURI_INVOKE("list_wake_words");
},
/**
 * Download a wake phrase (and the shared feature models on first use),
 * emitting `echo://wake-model-progress` (bare f32, 0..1).
 */
async downloadWakeModel(name: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_wake_model", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a user-trained `.onnx` classifier and select it. The shared feature
 * models are fetched first if this is the user's first wake model.
 */
async importWakeModel(path: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_wake_model", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the selected phrase can actually be loaded right now.
 */
async wakeWordReady() : Promise<boolean> {
    return await TAURI_INVOKE("wake_word_ready");
},
/**
 * Whether wake-word listening is currently armed.
 */
async wakeWordActive() : Promise<boolean> {
    return await TAURI_INVOKE("wake_word_active");
},
/**
 * Report why the wake word cannot run, for the settings UI to display.
 */
async wakeWordStatus() : Promise<Result<string, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wake_word_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Serialize history to a JSON file at the user-chosen path.
 * 
 * Exports everything, not the 100-row window the UI shows — an export the user
 * has to paginate is not an export.
 */
async exportHistory(path: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_history", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The identifier of the currently focused app, for the "add current app"
 * affordance in settings. `None` when the platform can't tell us — Wayland,
 * or macOS without Automation permission.
 */
async getForegroundApp() : Promise<Result<string | null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_foreground_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAppProfiles() : Promise<Result<AppProfile[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_app_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create or update the profile for an application. `app_match` is the
 * identifier [`get_foreground_app`] reports, and is stored lowercased.
 */
async saveAppProfile(profile: AppProfile) : Promise<Result<number, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_app_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAppProfile(id: number) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_app_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProfiles() : Promise<Result<Profile[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addProfile(name: string) : Promise<Result<number, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_profile", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a dictionary profile. Entries scoped to it become global again
 * (`ON DELETE CASCADE` is not used here — losing a user's phrases because they
 * deleted a grouping would be the wrong trade).
 */
async deleteProfile(id: number) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move a dictionary entry into a profile, or back to global with `None`.
 */
async setDictionaryEntryProfile(id: number, profileId: number | null) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_dictionary_entry_profile", { id, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEgressLog(limit: number | null) : Promise<Result<EgressRecord[], SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_egress_log", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearEgressLog() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_egress_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Summarise whether this configuration talks to anything.
 * 
 * This reports *configuration*, not observed behaviour — the log is the
 * behavioural half. Update checks are listed because the updater plugin makes
 * its own request that this module cannot instrument.
 */
async getEgressStatus() : Promise<Result<EgressStatus, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_egress_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a setting, falling back to the registry's default.
 * 
 * Returns `None` only for a key the registry does not have — which is a caller
 * bug, not a missing value.
 */
async getSetting(key: string) : Promise<Result<string | null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The whole settings surface in one call. See SettingsSnapshot.
 */
async settingsSnapshot() : Promise<Result<SettingsSnapshot, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Language codes that spoken punctuation actually has rules for.
 * 
 * Surfaced in settings so the list is a fact the user can read, rather than
 * something they discover by dictating "coma" and being ignored.
 */
async spokenPunctuationLanguages() : Promise<string[]> {
    return await TAURI_INVOKE("spoken_punctuation_languages");
},
/**
 * Language codes that number conversion has a parser for. Same reason as
 * [`spoken_punctuation_languages`].
 */
async numberLanguages() : Promise<string[]> {
    return await TAURI_INVOKE("number_languages");
},
/**
 * Language codes that filler and stutter cleanup has rules for. Same reason
 * as [`spoken_punctuation_languages`].
 */
async cleanupLanguages() : Promise<string[]> {
    return await TAURI_INVOKE("cleanup_languages");
},
/**
 * The dictation languages the settings picker and the tray submenu both
 * render — one list, so the two cannot drift.
 */
async dictationLanguages() : Promise<Language[]> {
    return await TAURI_INVOKE("dictation_languages");
},
/**
 * The facts a bug report needs, as the markdown block Echo pastes into one.
 * 
 * Built here rather than in the frontend because every line of it already
 * lives on this side — the settings table, the binary manager, the session
 * probe — and gathering it there would mean four round-trips and a second
 * place that has to know what "active" means for the GPU.
 * 
 * Deliberately small and readable: it is shown to the user in an editable box
 * before it goes anywhere, and a wall of JSON is not something anyone reads
 * before agreeing to publish it. Nothing here identifies the machine or the
 * person — no hostname, no username, no paths, no API keys.
 * 
 * ponytail: OS is the compile-time target, not the running build (no
 * "Windows 11 26100"). Add `os_info` if a report ever turns on a point
 * release.
 */
async diagnostics() : Promise<string> {
    return await TAURI_INVOKE("diagnostics");
},
/**
 * Show `echo.log` in the system file manager.
 * 
 * `init_tracing` calls that file "the only record a user can actually send
 * us", and until this there was no way to reach it from inside Echo — while
 * the bug report form asks for exactly that. Reveals the file rather than
 * opening it, because the thing people need is to attach it, and because a
 * long-running install's log is not something to hand to a text editor
 * unasked.
 * 
 * Falls back to the folder when the log is missing, which is what a run that
 * could not open it looks like (see `init_tracing`: logging is best effort).
 */
async openLog() : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Audio rescued from a session that ended without finishing — a crash, a
 * power cut, an OOM kill. Absolute paths, newest first, ready for
 * `transcribe_file`.
 * 
 * Empty is the normal answer, and the one the UI shows nothing for.
 */
async recoveredRecordings() : Promise<string[]> {
    return await TAURI_INVOKE("recovered_recordings");
},
/**
 * Delete one recovered recording, once the user is done with it.
 * 
 * The path comes from the frontend, so it is checked rather than trusted:
 * only a file this module would have created, and only in the data directory
 * it would have created it in. A `delete this path` command that took the
 * caller's word for it would be a gift to anything that could reach the IPC.
 */
async discardRecovered(path: string) : Promise<Result<null, SerializedError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_recovered", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the neural voice-activity model loaded at startup.
 * 
 * Settings offers a choice between it and the energy detector, and the choice
 * is a lie if the model never loaded — `start_recording` falls back to energy
 * whatever the setting says. So the picker asks, and says so when the answer
 * is no, rather than letting someone select a detector that is not running.
 */
async sileroAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("silero_available");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Per-app overrides. `None` on an override field means "inherit the global
 * setting", so a profile can pin one behaviour without freezing the rest.
 */
export type AppProfile = { id: number | null; 
/**
 * Lowercased executable name, bundle id, or window class, matched exactly.
 */
app_match: string; 
/**
 * Human-friendly name for the list; falls back to `app_match`.
 */
label: string | null; auto_inject: boolean | null; injection_method: string | null; 
/**
 * Type partial transcripts into this app as you speak. `None` inherits
 * the global setting.
 */
stream_partials: boolean | null; 
/**
 * Run the formatting pass in this app. `None` inherits the global setting.
 */
formatting: boolean | null; 
/**
 * Dictionary profile to apply while this app is focused.
 */
profile_id: number | null; enabled: boolean; 
/**
 * How the model should restyle text for this app ("formal, full
 * sentences"). `None` or blank means no rewrite; a style also needs the
 * global `app_style_enabled` switch. Defaulted so a caller that predates
 * the field still deserializes.
 */
style?: string | null }
export type AudioDevice = { name: string; is_default: boolean }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: Capability
 * * WHAT:  One feature of Echo, completely described.
 * * WHERE: The elements of registry::CAPABILITIES.
 * 
 */
export type Capability = { key: CapabilityKey; name: string; description: string; settings: SettingDef[]; 
/**
 * OS grants required before any command on this capability may run. The
 * command factory enforces this — handlers never check permissions.
 */
requires: OsPermission[]; nav: NavDef | null; metrics: MetricDef[]; hotkey: HotkeyDef | null }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: CapabilityKey
 * * WHAT:  The closed set of features Echo has.
 * * WHY:   An enum rather than a string, so a typo is a build error and a new
 * *        feature forces every exhaustive match to be revisited deliberately.
 * * WHERE: The identity of every registry entry; carried on every IPC command so
 * *        the factory knows which entry to preflight against.
 * 
 */
export type CapabilityKey = 
/**
 * The core loop: hotkey, record, transcribe, deliver.
 */
"DICTATION" | "HISTORY" | "INSIGHTS" | "DICTIONARY" | "MODELS" | "PROVIDERS" | "PLUGINS" | "PROFILES" | "WAKE_WORD" | "OUTPUT" | "PRIVACY" | "SETTINGS" | "ONBOARDING" | "UPDATES"
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: ChoiceSource
 * * WHAT:  Where a dynamic setting's options come from.
 * * WHY:   Input devices, installed models, cloud providers and supported
 * *        languages cannot be listed in a static declaration — they depend on
 * *        the machine, on what has been downloaded, and on which engine is
 * *        selected. Naming the SOURCE keeps the setting declarative anyway: the
 * *        registry still says what the control is, and the frontend resolves the
 * *        options, so adding a device picker stays a registry entry rather than
 * *        a bespoke form.
 * * WHERE: Carried by SettingKind::DynamicChoice; resolved by the SettingControl
 * *        component through the matching query command.
 * 
 */
export type ChoiceSource = "INPUT_DEVICES" | "WHISPER_MODELS" | "NEMO_MODELS" | "CLOUD_PROVIDERS" | 
/**
 * Languages the SELECTED engine declares support for — which is what stops
 * the UI offering a language on an engine that cannot speak it.
 */
"LANGUAGES" | 
/**
 * The languages a formatting stage actually has rules for, so "which
 * languages does this cover" is a fact to read rather than one to discover
 * by being ignored.
 */
"PUNCTUATION_LANGUAGES" | "NUMBER_LANGUAGES" | "CLEANUP_LANGUAGES" | "WAKE_WORD_MODELS" | "PROFILES"
/**
 * A single day's dictation, for the calendar.
 */
export type DayWords = { 
/**
 * ISO `YYYY-MM-DD`, local to whatever SQLite considers "now".
 */
date: string; words: number; transcripts: number }
/**
 * How much of the desktop the guard can see, on this machine, right now.
 * 
 * Surfaced in Settings beside the toggle, because the failure it describes is
 * silent: the guard is on, and where detection is missing it never fires.
 */
export type Detection = 
/**
 * Every app that publishes an accessibility tree can be asked.
 */
"available" | 
/**
 * Linux with accessibility switched off for the session: GTK apps answer,
 * Chromium, Electron and Qt apps publish nothing.
 */
"partial" | 
/**
 * Nothing can be asked — no accessibility bus, or no API on this platform.
 */
"unavailable"
/**
 * What dictation has added up to, derived from History.
 * 
 * Derived rather than counted separately: History already is the record, and a
 * second tally would be one more thing to keep in step with it. The cost is
 * that turning History off turns these off too, which the UI says.
 */
export type DictationStats = { transcripts: number; words: number; 
/**
 * Distinct days with at least one transcript.
 */
days: number; words_last_7_days: number; 
/**
 * Earliest transcript still stored, ISO-8601. History retention trims old
 * rows, so this is "since when the record goes back", not "since install".
 */
since: string | null }
export type DictionaryEntry = { id: number | null; phrase: string; replacement: string; enabled: boolean; profile_id: number | null; created_at: string }
/**
 * Portable representation of a dictionary entry for import/export (no ids or
 * timestamps so files move cleanly between machines).
 */
export type DictionaryExportEntry = { phrase: string; replacement: string; enabled?: boolean }
/**
 * What the Sync section shows. Persisted, so "last synced" survives a restart.
 */
export type DictionarySyncStatus = { last_synced_at: string | null; last_error: string | null; 
/**
 * Conflicted copies merged in on the last sync, by file name.
 */
conflict_copies?: string[] }
/**
 * One outbound request Echo made.
 */
export type EgressRecord = { id: number | null; host: string; purpose: string; created_at: string }
/**
 * Whether the current configuration is capable of reaching the network at all.
 */
export type EgressStatus = { 
/**
 * True when transcription, command mode and wake word are all local and no
 * cloud key is stored — i.e. normal use makes no requests.
 */
offline_capable: boolean; 
/**
 * Reasons the app can currently reach out, for display.
 */
reasons: string[]; 
/**
 * Requests logged in the last 24 hours.
 */
recent_count: number }
/**
 * Which local engine runs a model. The file name on disk follows from it, and
 * so does which provider can load it: a GGUF transducer means nothing to
 * whisper.cpp and a ggml whisper model means nothing to NeMo-Speech.
 */
export type Engine = "whisper" | "nemo"
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: ErrorCode
 * * WHAT:  The closed set of failures the frontend is allowed to branch on.
 * * WHY:   Stable identifiers, deliberately coarser than the error variants:
 * *        the UI cares whether it can retry, whether to send the user to a
 * *        settings pane, and whether to apologise — not which of four adapters
 * *        produced it.
 * * WHERE: Carried on every serialised EchoError.
 * 
 */
export type ErrorCode = 
/**
 * The input never should have reached a handler. Always a bug in the
 * caller, never something the user can act on.
 */
"INVALID_INPUT" | 
/**
 * An OS grant is missing. The UI sends the user to the right pane.
 */
"PERMISSION_REQUIRED" | 
/**
 * The engine is still starting. Transient by definition — see the module
 * WHY for why this one must not be drawn as a failure.
 */
"ENGINE_NOT_READY" | 
/**
 * The same exclusive command is already running.
 */
"ALREADY_IN_PROGRESS" | "AUDIO_DEVICE" | "TRANSCRIPTION" | "INJECTION" | "STORAGE" | "PLUGIN" | "CONFIG" | "NOT_FOUND"
/**
 * What the settings UI needs to show about compute: what was detected, what is
 * installed, and what is actually in use right now.
 */
export type GpuStatus = { 
/**
 * Human-readable detected backend, e.g. "NVIDIA CUDA 12.x".
 */
detected: string; 
/**
 * Id of the accelerated pack this machine could run, if any.
 */
available_pack: string | null; 
/**
 * Its download size in MB, so the user knows what they are agreeing to.
 */
available_pack_mb: number | null; 
/**
 * Whether that pack is downloaded.
 */
pack_installed: boolean; 
/**
 * Whether acceleration is actually being used for the next utterance.
 */
active: boolean; 
/**
 * True once an accelerated run failed and we latched to CPU.
 */
failed: boolean; 
/**
 * The user's opt-out.
 */
enabled: boolean; threads: number }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: HotkeyDef
 * * WHAT:  A global shortcut a capability binds, and its default.
 * * WHY:   Declared here so conflict detection has one list to check against
 * *        rather than discovering a clash at registration time, when the only
 * *        available response is a failure the user cannot interpret.
 * * WHERE: Read at startup by the hotkey commands and by the rebind UI.
 * 
 */
export type HotkeyDef = { 
/**
 * Stable id, e.g. "dictation.toggle".
 */
id: string; label: string; 
/**
 * Accelerator string in the form tauri-plugin-global-shortcut parses.
 */
default: string; 
/**
 * The setting key holding the user's override, if it is rebindable.
 */
setting_key: string | null }
/**
 * How well global hotkeys can be expected to work here.
 */
export type HotkeySupport = { session: SessionKind; 
/**
 * Desktop environment, when the session advertises one ("GNOME", "KDE").
 */
desktop: string | null; 
/**
 * Whether Echo can register the hotkey itself.
 */
can_bind: boolean; 
/**
 * Whether a modifier pressed on its own can be watched here.
 */
supports_bare_modifier: boolean; 
/**
 * Plain-language explanation, empty when everything works.
 */
advice: string }
/**
 * What a level test found.
 */
export type InputTest = { 
/**
 * Loudest sample heard, 0.0..=1.0.
 */
peak: number; 
/**
 * The same figure in dBFS, which is the scale every OS meter uses.
 */
peak_dbfs: number; 
/**
 * `"good"`, `"quiet"`, `"faint"` or `"silent"`.
 */
verdict: string; advice: string }
/**
 * Everything the Insights page shows, in one round trip.
 * 
 * Same source as [`dictation_stats`] — History — and the same consequence:
 * with History off there is nothing to count, and the page says so rather
 * than inventing numbers from a second tally nobody can inspect or delete.
 */
export type Insights = { transcripts: number; words: number; days: number; words_last_7_days: number; since: string | null; 
/**
 * Speech time and the words spoken in it, counted only over rows that
 * actually carry a duration. Words per minute is their ratio, and doing
 * it this way keeps rows recorded before durations existed from dragging
 * the rate down to nothing.
 */
spoken_ms: number; timed_words: number; timed_transcripts: number; dictionary_fixes: number; cleanup_fixes: number; 
/**
 * Consecutive days up to today (or yesterday, if today is still empty).
 */
streak: number; longest_streak: number; 
/**
 * Busiest first, and only what is known: apps go unrecorded on a machine
 * where Echo cannot see the focused window.
 */
apps: Tally[]; providers: Tally[]; languages: Tally[]; 
/**
 * Transcripts per hour of the day, 24 buckets starting at midnight.
 */
hours: number[]; 
/**
 * The last 365 days that had any dictation, oldest first.
 */
daily: DayWords[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Language = { 
/**
 * Whisper's code, and the value stored in the `language` setting.
 */
code: string; label: string }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: LatencyStage
 * * WHAT:  One measured leg of the path from keypress to text on screen.
 * * WHY:   Recorded against this enum, never a free string, so the insights
 * *        panel cannot end up querying a stage nothing writes — which is the
 * *        failure the reachability test exists to catch, expressed as a type.
 * *
 * *        The stages are cut at the boundaries a user would recognise, not at
 * *        the ones the code happens to have: everything before the first sample
 * *        is Capture, everything the model owns is Decode, everything after the
 * *        last token is Deliver. TotalFinalize is the one the product promises —
 * *        stop talking to text arriving — and it is deliberately measured
 * *        end-to-end rather than summed from the others, so a stage nobody
 * *        thought to time cannot hide inside it.
 * * WHERE: Written by the recorder below, declared by registry entries, read by
 * *        the insights panel.
 * 
 */
export type LatencyStage = 
/**
 * Hotkey press to the first audio sample reaching the pipeline. On a cold
 * microphone this is most of the answer to "why did it miss my first word".
 */
"CAPTURE_START" | 
/**
 * Text handed to the OS, to it landing in the focused app.
 */
"INJECT" | 
/**
 * Stop to delivered, measured end to end. The number the product promises.
 * 
 * Deliberately measured end to end rather than summed from the others, so
 * a stage nobody thought to time cannot hide inside it.
 */
"TOTAL_FINALIZE"
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: MetricDef
 * * WHAT:  A latency stage a capability is expected to emit.
 * * WHY:   Declaring metrics closes the loop in both directions: the insights
 * *        panel cannot read a stage nothing writes, and nothing can write a
 * *        stage that is never surfaced. Both are silent failures otherwise.
 * * WHERE: Written by core/telemetry/latency.rs, read by the insights queries.
 * 
 */
export type MetricDef = { stage: LatencyStage; label: string; 
/**
 * Shown on the insights latency panel rather than kept for diagnostics.
 */
user_facing: boolean }
/**
 * Information about a model returned to the frontend.
 */
export type ModelInfo = { name: string; downloaded: boolean; size_mb: number; english_only: boolean; 
/**
 * Which local engine runs it, so the UI can say what a model needs
 * installed before it can be selected.
 */
engine: Engine }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: NavDef
 * * WHAT:  A capability's placement in the window's nav rail.
 * * WHERE: Present means the capability appears in the nav; absent means it does
 * *        not. Read by the window shell.
 * 
 */
export type NavDef = { label: string; 
/**
 * Route segment, e.g. "history". Matched by the router.
 */
route: string; 
/**
 * Lucide icon name. Resolved by the frontend.
 */
icon: string; order: number }
export type NavEntry = { capability: CapabilityKey; nav: NavDef }
/**
 * What the UI needs to offer the NeMo engine: whether each half is present,
 * and what installing the missing half would cost.
 */
export type NemoStatus = { 
/**
 * Binaries and the selected model are both present.
 */
ready: boolean; engine_installed: boolean; model_downloaded: boolean; model: string; 
/**
 * Size of the engine download for this machine, in megabytes.
 */
engine_mb: number; 
/**
 * Which build would be installed ("CPU" / "NVIDIA CUDA").
 */
engine_label: string }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: OsPermission
 * * WHAT:  An operating-system grant a feature cannot work without.
 * * WHY:   Declared per capability so the command factory can turn a missing
 * *        grant into a typed, actionable error before a handler runs, rather
 * *        than each adapter discovering it separately and failing in its own
 * *        dialect. Echo already asks the OS these two questions; what it did
 * *        not have was one name for the answer.
 * * WHERE: On Capability::requires and SettingDef::requires_permission; checked
 * *        by ipc/factory.rs::preflight_permissions.
 * 
 */
export type OsPermission = 
/**
 * Recording. Without it there is no audio at all.
 */
"MICROPHONE" | 
/**
 * Typing into another app, and reading which app is focused. Without it
 * Echo still transcribes and still reaches the clipboard.
 */
"ACCESSIBILITY"
/**
 * Summary of an installed plugin returned to the frontend.
 */
export type PluginInfo = { name: string; version: string; description: string; author: string; enabled: boolean; 
/**
 * What the plugin *declares* it needs. Advisory — see [`PluginPermission`].
 * Surfaced so a user can at least see what was claimed before enabling it.
 */
permissions?: PluginPermission[] }
/**
 * Manifest shipped alongside a plugin as `plugin.json`.
 */
export type PluginManifest = { name: string; version: string; description?: string; author?: string; permissions?: PluginPermission[]; 
/**
 * Shared-library file name (e.g. `my_plugin.dll`).
 */
entry: string }
/**
 * Declared capabilities a plugin may request in its manifest. The permission
 * model is advisory in this version (plugins run in-process); true sandboxing
 * (e.g. a WASM runtime) is a future goal.
 * 
 * What Echo actually calls is decided by the `as_*` methods on [`Plugin`], not
 * by this list: declaring `output` without implementing it gets no calls, and
 * implementing it without declaring it still does. The list is what the user
 * is shown before installing, so keep the two in agreement.
 */
export type PluginPermission = "asr" | "output" | "audio" | "dictionary"
export type Profile = { id: number | null; name: string; created_at: string; updated_at: string }
/**
 * A provider as the settings UI needs it: shape, plus whether a key is stored
 * and what the user has chosen. Never carries the key itself.
 */
export type ProviderInfo = 
/**
 * Flattened by value rather than by reference: specta cannot describe a
 * flattened `&'static T` for the generated bindings, and a ProviderSpec is
 * a handful of `&'static str` — cloning one costs nothing and the list is
 * built once per settings open.
 */
({ id: string; label: string; kind: ProviderKind; 
/**
 * API root, not the full transcription path. Empty when the user must
 * supply it (`needs_endpoint`).
 */
default_endpoint: string; 
/**
 * Suggested models, most common first. `models[0]` is the default, so
 * reordering this changes what existing users get — don't, casually.
 * Empty means the provider has no model choice, or only a free-text one.
 */
models: string[]; 
/**
 * The user must provide the endpoint; there is no sensible default.
 */
needs_endpoint: boolean; 
/**
 * The user must provide a region — the host itself depends on it.
 */
needs_region: boolean; 
/**
 * Echo can ask this provider who spoke when transcribing an imported
 * recording — see [`super::AsrProvider::transcribe_speakers`]. The import
 * panel reads it to enable its "Label speakers" box and to name the
 * providers that would, so a row set `true` must implement that method.
 * 
 * Google stays `false` even though its API can diarize: Echo uses the
 * synchronous endpoint, which refuses anything past sixty seconds, and a
 * recording worth labelling is longer than that. OpenAI's diarizing model
 * is one model behind an endpoint shared with Groq, Mistral and every
 * self-hosted clone, so it is not a per-row fact either.
 */
speaker_labels: boolean; docs_url: string; 
/**
 * Shown under the provider in Settings. Use it for the things people
 * discover the hard way: latency, hard limits, where the key travels.
 */
note: string }) & { key_set: boolean; model: string; endpoint: string; region: string | null; 
/**
 * False while a catalog row exists but its provider is not built yet.
 */
available: boolean }
/**
 * How a provider's HTTP conversation actually goes.
 * 
 * The variants are grouped by request shape rather than by vendor, because
 * that is what determines whether a vendor costs new code: everything
 * [`ProviderKind::OpenAiCompatible`] shares one implementation.
 */
export type ProviderKind = 
/**
 * `POST {base}/audio/transcriptions`, multipart, bearer auth.
 * OpenAI, Groq, Mistral, and every self-hosted clone.
 */
"open_ai_compatible" | 
/**
 * Raw-body POST with query params, `Token` auth. Also the only provider
 * with a real streaming socket.
 */
"deepgram" | 
/**
 * Multipart with an `xi-api-key` header and `model_id`/`file` fields.
 */
"eleven_labs" | 
/**
 * Multipart `audio` + `definition` JSON against a regional host.
 */
"azure_speech" | 
/**
 * Upload bytes, create a job, then poll it.
 */
"assembly_ai" | 
/**
 * Multipart job submission, then poll.
 */
"speechmatics" | 
/**
 * JSON with base64 audio inline, key in the query string.
 */
"google_stt"
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: SerializedError
 * * WHAT:  The wire shape of an error: code, message, and whether retrying could
 * *        help.
 * * WHY:   A struct rather than the bare string this used to be, so the UI has
 * *        something to branch on that survives a copy edit. `message` stays
 * *        first-class and human — the code tells the UI what to DO, the message
 * *        tells the user what happened, and neither is derivable from the other.
 * * WHERE: Produced by the Serialize impl below; consumed by src/lib/errors.ts.
 * 
 */
export type SerializedError = { code: ErrorCode; message: string; recoverable: boolean }
/**
 * The windowing system in use, as far as we can tell from the environment.
 */
export type SessionKind = 
/**
 * Windows or macOS, where application-registered global hotkeys work.
 */
"native" | 
/**
 * X11, including XWayland — global hotkeys work.
 */
"x11" | 
/**
 * Wayland — an application cannot claim a global hotkey for itself.
 */
"wayland" | 
/**
 * No graphical session we recognise.
 */
"unknown"
export type SettingChoice = { value: string; label: string; description: string | null }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: SettingDef
 * * WHAT:  One setting, fully described: how it renders, what it defaults to, and
 * *        what it requires to be usable.
 * * WHY:   `default` is typed as SettingValue and validated against `kind` at
 * *        startup, so a mismatch is caught the first time the app runs rather
 * *        than the first time a user opens that pane.
 * *
 * *        `requires_permission` is what lets settings explain that a toggle
 * *        cannot do anything instead of offering one that silently fails. A
 * *        toggle that is ON while the permission behind it is missing is a
 * *        control that lies: the user has said yes, the app agrees, and nothing
 * *        happens.
 * * WHERE: Declared in registry/mod.rs; rendered by the SettingControl component;
 * *        enforced on write by the settings service.
 * 
 */
export type SettingDef = { 
/**
 * Globally unique, stable. This is the database key — renaming one
 * silently resets that setting for every existing user.
 */
key: string; label: string; description: string; section: SettingSection; kind: SettingKind; default: SettingValue; 
/**
 * OS grants without which this setting cannot do anything, whatever its
 * value.
 */
requires_permission: OsPermission[]; 
/**
 * Hidden behind a disclosure. For settings that exist to unstick a
 * specific machine, not ones people are expected to browse.
 */
advanced: boolean; 
/**
 * Shown only when another setting has one of a set of values. None means
 * always shown.
 */
visible_when: VisibleWhen | null }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: SettingKind
 * * WHAT:  How a setting renders, and what values it will accept.
 * * WHERE: On every SettingDef; the settings view switches its control on this
 * *        and on nothing else.
 * 
 */
export type SettingKind = { type: "TOGGLE" } | { type: "TEXT"; placeholder: string | null; max_len: number | null } | { type: "NUMBER"; min: number; max: number; step: number; unit: string | null } | { type: "CHOICE"; options: SettingChoice[] } | 
/**
 * A choice whose options are only knowable at runtime.
 */
{ type: "DYNAMIC_CHOICE"; source: ChoiceSource } | { type: "HOTKEY" }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: SettingSection
 * * WHAT:  Which page and section of the settings window a setting renders in.
 * * WHY:   Grouping is presentation, but it belongs to the DECLARATION. A setting
 * *        that does not say where it goes forces the settings view to keep its
 * *        own ordering list, which is the exact duplication the registry exists
 * *        to remove — and that list is the thing that silently goes stale when a
 * *        setting is added.
 * *
 * *        The variants are page-and-section rather than a coarse topic, because
 * *        the window is split that way: four pages, each with its own tabs, and
 * *        a setting placed only to the page would still need a second list to
 * *        decide its tab. Written as `PageSection` in one name so a setting
 * *        declares its whole home in one value.
 * *
 * *        `*Advanced` sections are for settings that exist to unstick a specific
 * *        machine. That is a different question from `SettingDef::advanced`,
 * *        which hides a row behind a disclosure within whatever section it is
 * *        in; a setting can be in an Advanced section without being hidden, and
 * *        usually is.
 * * WHERE: On every SettingDef; read by the settings view to place its controls.
 * 
 */
export type SettingSection = "SETTINGS_GENERAL" | "SETTINGS_DICTATION" | "SETTINGS_MICROPHONE" | "ENGINE_SPEECH" | 
/**
 * Holds no settings — only the file-transcription and crash-recovery
 * blocks. A section can be all EXTRAS: audio a crash interrupted is
 * something nobody would think to look for on a tab they did not know
 * existed, so it gets a name of its own rather than being tucked under
 * Advanced.
 */
"ENGINE_TOOLS" | "ENGINE_ADVANCED" | "OUTPUT_INSERT" | "OUTPUT_FORMATTING" | "OUTPUT_APPS" | "OUTPUT_ADVANCED" | "PRIVACY"
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: SettingValue
 * * WHAT:  A stored setting value, closed over the kinds above.
 * * WHY:   Validating a value against its declared kind is only possible because
 * *        both are typed. Echo stores settings as strings in SQLite and will
 * *        keep doing so — this type is the shape they are validated as on the
 * *        way in and handed to the UI as, so "true" for a Number is rejected at
 * *        the boundary rather than surfacing as an `unwrap_or` three layers
 * *        down quietly substituting a default.
 * * WHERE: Produced and validated by services/settings.rs against the registry's
 * *        SettingDef before a write is accepted.
 * 
 */
export type SettingValue = { type: "BOOL"; value: boolean } | { type: "TEXT"; value: string } | { type: "NUMBER"; value: number }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: SettingsSnapshot
 * * WHAT:  Everything the settings window needs to render itself: the capability
 * *        table, and the value of every setting.
 * * WHY:   One round trip rather than one per control. The window opens with
 * *        forty-odd settings on it, and forty sequential IPC calls is a visible
 * *        stagger as each control pops in with its real value.
 * * WHERE: Produced by `settings_snapshot`; consumed by the settings view.
 * 
 */
export type SettingsSnapshot = { 
/**
 * The registry table, verbatim. The frontend renders controls from this
 * and holds no second copy of what the app has.
 */
capabilities: Capability[]; 
/**
 * Current value per key, already defaulted. Every key in the registry is
 * present, so the frontend never has to decide what missing means.
 */
values: StoredSetting[]; 
/**
 * Nav entries in rail order, so the shell does not re-sort them.
 */
nav: NavEntry[] }
/**
 * A voice snippet: say `trigger` as a whole utterance, get `body` verbatim.
 * See [`crate::core::snippets`] for why this is not a dictionary entry.
 */
export type Snippet = { id: number | null; trigger: string; 
/**
 * Delivered exactly as stored — line breaks, numbers and punctuation
 * included. Never formatted.
 */
body: string; enabled: boolean }
export type StoredSetting = { key: string; value: string; 
/**
 * False when the stored row is absent and this is the registry's default.
 * The UI uses it to offer "reset" only where there is something to reset.
 */
is_set: boolean }
/**
 * One row of a "how much of it was X" breakdown — an app, a provider, a
 * language. Three questions with the same shape, so they share one answer.
 */
export type Tally = { key: string; transcripts: number; words: number }
/**
 * Aggregated count of telemetry events of one type.
 */
export type TelemetrySummaryItem = { event_type: string; count: number }
export type TranscriptionRecord = { id: number | null; text: string; language: string | null; provider: string; created_at: string; 
/**
 * How long you spoke, from the speech the VAD actually forwarded. `None`
 * for rows written before this was measured, and for any utterance whose
 * duration could not be established — a missing number, not a zero.
 */
duration_ms?: number | null; 
/**
 * The app that was focused when the text was delivered, lowercased, in
 * the same form per-app profiles match on.
 */
app?: string | null; 
/**
 * Words the dictionary rewrote.
 */
dictionary_fixes?: number; 
/**
 * Words the clean-up pass changed — fillers dropped, punctuation spoken,
 * numbers written as digits.
 */
cleanup_fixes?: number }
/**
 * 
 * * SOURCE OF TRUTH KEYWORDS: VisibleWhen
 * * WHAT:  A condition on ANOTHER setting that decides whether this one is shown.
 * * WHY:   Some controls only mean anything for certain values of another. The
 * *        clipboard hold is the worked example: it says how long to let the
 * *        target app read the clipboard, and Echo only borrows the clipboard
 * *        when it is pasting — so on "always type" the control is there,
 * *        adjustable, and governs nothing.
 * *
 * *        Declared rather than coded in the view, for the same reason placement
 * *        is: a condition living in the frontend is a second place that has to
 * *        learn about every new setting, and the one that silently goes stale.
 * *
 * *        Deliberately only "this key is one of these values" — not an
 * *        expression language. Every condition the app actually has fits, and a
 * *        richer form would invite logic into a table that other layers have to
 * *        be able to read without evaluating anything.
 * * WHERE: On SettingDef::visible_when; honoured by the settings view.
 * 
 */
export type VisibleWhen = { 
/**
 * The setting this one depends on.
 */
key: string; 
/**
 * Values of that setting for which this control is shown.
 */
any_of: string[] }
/**
 * A wake phrase and its local availability, for the settings UI.
 */
export type WakePhraseInfo = { id: string; label: string; downloaded: boolean; 
/**
 * True for a user-imported model rather than a catalog entry.
 */
custom: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
